// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMl2mMMUqa2xrFoNVeD9-kZBJeOfEvEeY',
    appId: '1:214325242886:web:21bba4f59d8031d4926787',
    messagingSenderId: '214325242886',
    projectId: 'bloodpressureapp-bba65',
    authDomain: 'bloodpressureapp-bba65.firebaseapp.com',
    storageBucket: 'bloodpressureapp-bba65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFUUDifZ3pSEaNSONgZYm8LdPGtLObmWI',
    appId: '1:214325242886:android:4d08e139132816c5926787',
    messagingSenderId: '214325242886',
    projectId: 'bloodpressureapp-bba65',
    storageBucket: 'bloodpressureapp-bba65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lwIvgaVRfwuhw2cIJ_WiflRb2mahuYA',
    appId: '1:214325242886:ios:0e3a695f96554aca926787',
    messagingSenderId: '214325242886',
    projectId: 'bloodpressureapp-bba65',
    storageBucket: 'bloodpressureapp-bba65.firebasestorage.app',
    iosBundleId: 'com.example.bloodPressureApp',
  );

}