// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ2pU8EsdKJ5qIlJsFRppk5YavP-mH5EY',
    appId: '1:774035192078:web:939bcc45a974d066e3ff5f',
    messagingSenderId: '774035192078',
    projectId: 'guardpulse-da795',
    authDomain: 'guardpulse-da795.firebaseapp.com',
    storageBucket: 'guardpulse-da795.firebasestorage.app',
    measurementId: 'G-XJEZ1EW3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNfckpu3saAqofrZkRnw6B-ovBy8RvdQ',
    appId: '1:774035192078:android:3b71850b6cd02886e3ff5f',
    messagingSenderId: '774035192078',
    projectId: 'guardpulse-da795',
    storageBucket: 'guardpulse-da795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17eKBTzXb6FHG2Vn2lyMym-leV5j2zQA',
    appId: '1:774035192078:ios:f7e9b1e62809a552e3ff5f',
    messagingSenderId: '774035192078',
    projectId: 'guardpulse-da795',
    storageBucket: 'guardpulse-da795.firebasestorage.app',
    iosBundleId: 'com.example.bloodPressureApp',
  );
}
